wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random_page", views.random_page, name="random_page"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from markdown2 import Markdown

import random



from . import util

class SearchForm(forms.Form):
    q = forms.CharField(label="Search Encyclopedia")

class CreateForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(label="Content")
  
def index(request):
    """
    Displays the index page.
    """
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def create(request):
    """
    Displays the create page.
    """
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = CreateForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the title and content from the 'cleaned' version of form data
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            # Check if the title already exists
            if util.get_entry(title) is None:
                util.save_entry(title, content)
                return render(request, "encyclopedia/entry.html", {
                    "title": title,
                    "content": util.get_entry(title)
                })
            else:
                return render(request, "encyclopedia/error.html", {
                    "message": "Entry already exists"
                })
            
        else:

            # If the form is invalid, re-render the page with existing information.
            return render(request, "encyclopedia/error.html", {
                "message": "Invalid form"
            })
    else:

        # If the request method is not POST, render the page with a blank form.
        return render(request, "encyclopedia/create.html", {
            "form": CreateForm()
        })

def entry(request, title):
    """
    Displays the requested entry.
    """
    # If the entry does not exist, display an error message
    entry_content = util.get_entry(title)
    if entry_content is None:
        return render(request, "encyclopedia/error.html", {
            "message": "Entry not found"
        })
    else:
        # If the entry exists, display it
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": Markdown().convert(entry_content),
        })
    
def edit(request, title):
    """
    Displays the edit page.
    """
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = CreateForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the title and content from the 'cleaned' version of form data
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            util.save_entry(title, content)

            return render(request, "encyclopedia/entry.html", {
                "title": title,
                "content": util.get_entry(title)
            })
            
        else:

            # If the form is invalid, re-render the page with existing information.
            return render(request, "encyclopedia/error.html", {
                "message": "Invalid form"
            })
    else:

        # If the request method is not POST, render the page with a blank form.
        return render(request, "encyclopedia/edit.html", {
            "form": CreateForm(initial={'title': title, 'content': util.get_entry(title)}),
            "title": title,
            "content": util.get_entry(title),
        })
    
def random_page(request):
    """
    Displays a random entry.
    """    

    entries = util.list_entries()
    if not entries:
        return render(request, "encyclopedia/error.html", {
            "message": "No entries found"
        })
    title = random.choice(entries)
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": util.get_entry(title)
    })

    
def search(request):
    """
    Displays the search results.
    """
    if request.method == "POST":

        # Take in the data the user submitted and save it as form
        form = SearchForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the q from the 'cleaned' version of form data
            q = form.cleaned_data["q"]

            # Search for the q in the list of entries
            entries = util.list_entries()

            results = []

            # If the q is in the entry, add it to the results list
            for entry in entries:
                if q.lower() in entry.lower():
                    results.append(entry)

            # If the q is an exact match for an entry, redirect to that entry page
            if q in results:
                return render(request, "encyclopedia/entry.html", {
                    "title": q,
                    "content": util.get_entry(q)
                })
            
            # If the q does not match any entries, display a message
            elif len(results) == 0:
                return render(request, "encyclopedia/error.html", {
                    "message": "No results found"
                })
            
            # If the q matches multiple entries, display a list of those entries
            else:
                return render(request, "encyclopedia/search.html", {
                    "results": results
                })
            
        else:

            # If the form is invalid, re-render the page with existing information.
            return render(request, "encyclopedia/error.html", {
                "message": "Invalid form"
            })
    else:

        # If the request method is not POST, re-render the page with existing information.
        return render(request, "encyclopedia/error.html", {
            "message": "Invalid request"
        })
    

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
    <form action="{% url 'wiki:create' %}" method="post">
        {% csrf_token %}
        <input type="text" name="title" placeholder="Title">
        <textarea name="content" placeholder="Content"></textarea>
        <input type="submit" value="Create">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>
    
    <form action="{% url 'wiki:edit' title %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ title }}">
        <textarea name="content" placeholder="Content">{{ content }}</textarea>
        <input type="submit" value="Edit">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div class="entry">
        {{ content|safe }}
    </div>
    <a href="{% url 'wiki:edit' title %}">Edit</a>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <div class="error">
        {{ message }}
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="/wiki/{{ entry }}">
                    {{ entry }}
                </a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
            
                <form action="{% url 'wiki:search' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="title" value="Special:Search">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                
                <div>
                    <a href="{% url 'wiki:index' %}">
                        Home
                    </a>
                </div>
                
                <div>
                    <a href="{% url 'wiki:create' %}">
                        Create New Page
                    </a>
                </div>
                
                <div>
                    <a href="{% url 'wiki:random_page' %}">
                        Random Page
                    </a>
                </div>
                
                {% block nav %}
                {% endblock %}
            
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <ul>
        {% for result in results %}
            <li>
                <a href="/wiki/{{ result }}">
                    {{ result }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}
       
    